title: "Sergio Picella Personal website"
description: "Get to know what I do in life, what I like, what to I do to call it a day!"
theme: jekyll-theme-minimal
layout: page
show_downloads: false
header_pages:
  - academic.md
  - life.md
  
twitter_username: SergioPicella
github_username:  spicella
facebook_username: Sergio Picella
instagram_username: sergiopc8
linkedin_username: Sergio Picella

rss: rss
