title: "Sergio Picella Personal website"
description: "Get to know what I do in life, what I like, what to I do to call it a day!"
theme: jekyll-theme-minimal
layout: page
show_downloads: false
header_pages:
  - about.md
  - portfolio.md
sidebar: toc


---
Title: Sample 1
category: getting-started
order: 1
---

---
Title: Sample 2
category: getting-started
order: 2
---
