title: "Sergio Picella, Personal website"
description: "Get to know who I am, what I like, what I do to call it a day!"
theme: jekyll-theme-minimal
show_downloads: false
header_pages:
  - about.md
  - academic.md
  - contacts.md
sidebar: toc


---
Title: Sample 1
category: getting-started
order: 1
---

---
Title: Sample 2
category: getting-started
order: 2
---
