title: "Personal Website"
description: Get to know what I do in life, what I like, what to I do to call it a day! 

theme: jekyll-theme-minimal
layout: page
logo: ![profilephoto](https://raw.githubusercontent.com/spicella/SergioPicella/master/imgs/coffee.jpg)
show_downloads: false

